export const NAME_SCREEN = {
  SPLASH_SCREEN: {
    TO_LOGIN_SCREEN: 'TO_LOGIN_SCREEN',
  },

  LOGIN_SCREEN: {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  },

  DRAWER_SCREEN: {
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  },

  GLOBAL: {
    SHOW_EDIT_PROJECT_DETAIL_SCREENS: 'SHOW_EDIT_PROJECT_DETAIL_SCREENS',
    HIDE_EDIT_PROJECT_DETAIL_SCREENS: 'HIDE_EDIT_PROJECT_DETAIL_SCREENS',
    SHOW_IS_LOADING: 'SHOW_IS_LOADING',
    HIDE_IS_LOADING: 'HIDE_IS_LOADING',
    GET_URL: 'GET_URL',
  },

  PROJECT: {
    GET_LIST_PROJECT_SCREENS: 'GET_LIST_PROJECT_SCREENS',
    GET_PROJECT_DETAILS_ITEMS_SCREENS: 'GET_PROJECT_DETAILS_ITEMS_SCREENS',
    GET_LIST_USER_MANAGER: 'GET_LIST_USER_MANAGER',
    GET_LIST_USER_ADD: 'GET_LIST_USER_ADD',
    GET_ITEMS_ADD_USER: 'GET_ITEMS_ADD_USER',
    DELETE_ITEMS_USER: 'DELETE_ITEMS_USER',
    GET_LIST_PROJECT_TYPE: 'GET_LIST_PROJECT_TYPE',
    UPDATE_PROJECT_AFTER_EDIT: 'UPDATE_PROJECT_AFTER_EDIT',
    ADD_USERS_FROM_CHECKBOX: 'ADD_USERS_FROM_CHECKBOX',
    LIST_TASK_IN_PROJECT_DETAIL: 'LIST_TASK_IN_PROJECT_DETAIL'
  },

  SETTING_SCREEN: {
    CHANGE_ENGLISH: 'CHANGE_ENGLISH',
    CHANGE_VIETNAMESE: 'CHANGE_VIETNAMESE',
  },

  TASK_SCREEN: {
    GET_LIST_TASK: 'GET_LIST_TASK',
    GET_LIST_SPRINT: 'GET_LIST_SPRINT',
    GET_LIST_PROJECTTYPE: 'GET_LIST_PROJECTTYPE',
  },

  TASK_DETAIL_SCREEN: {
    GET_TASK_DETAIL: 'GET_TASK_DETAIL',
  },
};
